# Generated by Django 5.1 on 2024-08-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Qr1', 'QR1'), ('Qr2', 'QR2'), ('Qr3', 'QR3')], max_length=3)),
                ('completed', models.BooleanField(default=False)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.serialnumber')),
            ],
        ),
    ]
