# Generated by Django 5.1 on 2024-08-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr1_completed', models.BooleanField(default=False)),
                ('qr2_completed', models.BooleanField(default=False)),
                ('qr3_completed', models.BooleanField(default=False)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.serialnumber')),
            ],
        ),
    ]
