# Generated by Django 5.1 on 2024-08-27 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_stagecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stagecompletion',
            name='qr1_completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagecompletion',
            name='qr2_completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagecompletion',
            name='qr3_completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
